apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: phone-book-frontend
  name: phone-book-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      service: phone-book-frontend
  template:
    metadata:
      labels:
        service: phone-book-frontend
    spec:
      containers:
      - image: diehlp/phone-book-frontend
        name: phone-book-frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                
      restartPolicy: Always