apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: phone-book-reverseproxy
  name: phone-book-reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udagram-reverseproxy
  template:
    metadata:
      labels:
        service: udagram-reverseproxy
    spec:
      containers:
      - image: diehlp/phone-book-reverseproxy
        name: phone-book-reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always