apiVersion: v1
kind: Service
metadata:
  labels:
    service: phone-book-reverseproxy
  name: phone-book-reverseproxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: phone-book-reverseproxy